# Generated by Django 5.2.1 on 2025-05-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100)),
                ('datefact', models.DateField(null=True)),
                ('textfact', models.TextField(null=True)),
                ('total', models.FloatField(default=0, null=True)),
                ('details', models.TextField(null=True)),
                ('compte', models.CharField(null=True)),
                ('categ', models.CharField(null=True)),
            ],
        ),
    ]
