# Generated by Django 5.2.1 on 2025-06-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='path',
            field=models.TextField(null=True),
        ),
    ]
