# Generated by Django 5.2.1 on 2025-06-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_facture_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='tva',
            field=models.FloatField(default=0, null=True),
        ),
    ]
